### ISSUE TITLE
Would It Be Possible To Be Able To Specify Which Branch(es) To Publish?

### ISSUE THREAD

**Issue by yannduran** [nkdAgility/azure-devops-git-tools#2]
I'm currently using two *Command Line* tasks to sync my VSTS Git repo to GitHub, one to pull from the GitHub repo and the other to push to it.

I was hoping to be able to replace them with your task, but I can't see a way to specify which branch(es) to sync. I have both a *development* branch and a *master* branch, but I only want to sync the **master** branch to GitHub.

Am I missing something, or was the intent behind your extension to publish **all** branches? If so, would it be possible to add the ability to select which branch(es) to publish?

**Comment by MrHinsh** [comment]
It currently publishes all branches. I would happily accept a pull request for this.

**Comment by yannduran** [comment]
OK, I'll see what I can do - thanks!
